### ISSUE TITLE
Associate Docker icon with `.dockerignore`

### ISSUE THREAD

**Issue by ihodev** [ihodev/a-file-icon#103]

**Comment by Pegase745** [comment]
@ihodev possible to associate that with the Dockerfile too please ?

**Comment by ihodev** [comment]
@Pegase745 For `Dockerfile` just install [syntax](https://packagecontrol.io/packages/Dockerfile%20Syntax%20Highlighting). More details [here](https://github.com/ihodev/a-file-icon/blob/develop/PACKAGES.md).

**Comment by Pegase745** [comment]
great, thanks !
