### ISSUE TITLE
Why its settings are inacessibilidade?

### ISSUE THREAD

**Issue by evandrocoan** [ihodev/a-file-icon#118]
![image](https://cloud.githubusercontent.com/assets/5332158/26022758/a167fc9c-3783-11e7-9c6e-6ee5fe1b0c9a.png)

My Sublime Text version is 3114.

**Comment by ihodev** [comment]
@evandrocoan That's because settings command requires ST 3124+:

```
Build 3124
Settings now open in a new window, with the default and user settings side-by-side
```

Just create `Packages/User/A File Icon.sublime-settings` and customize [these ones](https://github.com/ihodev/a-file-icon/blob/develop/.sublime/A%20File%20Icon.sublime-settings). I don't want to provide legacy settings commands.

**Comment by evandrocoan** [comment]
Thanks
