### ISSUE TITLE
the vue file has no icon

### ISSUE THREAD

**Issue by lee-mz** [ihodev/a-file-icon#128]
i installed the A File Icon plugins with st3 packageControll.
When i create a file with the suffix named .vue
it has no icon.
can you help me?
thanks!
As shown below:
![pic](https://user-images.githubusercontent.com/7866014/28700590-49c720bc-7383-11e7-980a-0da3db6f786f.jpg)

**Comment by xlongye** [comment]
install plugin: Vue Syntax Highlight

**Comment by lee-mz** [comment]
@xlongye thanks!
