### ISSUE TITLE
Icons are not show after to setup A File Icon

### ISSUE THREAD

**Issue by AnhQuanTran** [ihodev/a-file-icon#130]
Icons are not show after to setup A File Icon
I use sublime text build 3059 on windows 10,  theme Spacegray and color scheme 1337 
Setup package a file icon with guide: ( because i can not find package A File Icon on package control )
1. Download the .zip
2. Unzip and rename folder to A File Icon
3. Copy folder into Packages directory, which you can find using the menu item Preferences → Browse Packages...
4. Restart Sublime Text after installing this package.

I can not find package A File Icon on package control 
![image](https://user-images.githubusercontent.com/21956433/29651844-df4b0d66-88cc-11e7-9d45-4a5758a4ed20.png)

Options for setting packge A File Icon 
![image](https://user-images.githubusercontent.com/21956433/29651851-e54250b2-88cc-11e7-854a-61421d1bc66e.png)

Help me
Thanks

**Comment by ihodev** [comment]
Sorry, this package doesn't support such old ST builds, that's why you can't find it on PC. Even more when next stable ST3 will be released `A File Icon` requires it. Please consider upgrading.
