### ISSUE TITLE
Add ability to see icons under "Open Files"

### ISSUE THREAD

**Issue by alexkadis** [ihodev/a-file-icon#131]
Is it currently possible to set up the ability to see icons next to open files? If not, I would like to add that as a feature request.

![Open Files](https://i.imgur.com/mB4yzUK.png)

I would be happy to work on this feature, just not sure how to start.

**Comment by ihodev** [comment]
@alexkadis Sorry, currently that's not possible and [in the near future won't be possible too](https://github.com/SublimeTextIssues/Core/issues/1595#issuecomment-315863491) 😞

**Comment by alexkadis** [comment]
Thanks @ihodev for the quick reply. Not the news I was hoping for. So it goes.
