### ISSUE TITLE
Usage of SVG or font icons

### ISSUE THREAD

**Issue by mittalyashu** [ihodev/a-file-icon#141]
Isn't it will be great to convert all the icons to SVG in that way the icons will be crisp, no matter how much is the size.

See, what happens, when we increase the size of icons.
![image](https://user-images.githubusercontent.com/29014463/31078833-47d6bbd0-a7a1-11e7-8fd6-9ceb7f283a6c.png)

**Comment by ihodev** [comment]
Unfortunately, ST doesn't support:

* SVG icons,
* Font icons.

That's why we convert `svg` to `png`.

**Comment by ihodev** [comment]
ST devs have no plans to add support of svg icons in the near future.
