### ISSUE TITLE
New icons request for .kit

### ISSUE THREAD

**Issue by mittalyashu** [ihodev/a-file-icon#144]
Can you add an icon for .kit language?

**Comment by ihodev** [comment]
https://codekitapp.com/help/kit/ this one?

**Comment by mittalyashu** [comment]
Yup.

See, it doesn't have any icon for kit.
![image](https://user-images.githubusercontent.com/29014463/31177779-aaca7f4e-a934-11e7-8200-5256ca19c454.png)

**Comment by ihodev** [comment]
Ok, as that's just a regular HTML, you we don't need any additions. Just open `index.kit` and then `View → Syntax → Open all with current extension as... → HTML`.
