### ISSUE TITLE
Not working with Sublime Text 2

### ISSUE THREAD

**Issue by dkjain** [ihodev/a-file-icon#148]
Does this not work with ST2 ? After Installing via zip file download method. "A file Icon" is disabled.

![file_icon_disabled](https://user-images.githubusercontent.com/10743577/32134793-22e9dec6-bc12-11e7-8630-621c3415e465.png)

![a_file_icon_package-in-packages_directory](https://user-images.githubusercontent.com/10743577/32134801-5c0331c6-bc12-11e7-92bf-a4cf15768246.png)

**Comment by ihodev** [comment]
No, it does not and I have no plans to support ST2.
